### ISSUE TITLE
不同网站的验证码识别效果不佳

### ISSUE THREAD

**Issue by chyun** [alingse/verifycode#1]
Hello, 请教一下哈, 使用该项目中的方法,针对某个网站训练, 效果很不错, 但是不同网站之间, 由于图片尺寸不同, 背景色不同等原因,  跨网站识别的话效果不佳, 不知道您这边有没有考虑过这个问题, 有没有啥解决方案?

**Comment by alingse** [comment]
我准备学习机器学习了， 🐶 。。。（将来学好了再试一下
这个代码其实只能逐网站自己来训练，对简单的验证码可以的。
